---
# tasks file for win_ad_install

- hosts: all
  tasks:
  - name: Check Windows server
    win_ping:
    when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  - name: Check Linux servers
    ping:
    when: ansible_distribution != "Microsoft Windows Server 2012 R2 Standard"
  - tags:
      - pingtest

- name: install ad domain services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes

- name: setup ad controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_controllers

- name: reboot windows
  win_reboot:
  when: ad_controllers.reboot_required

- name: list domain controllers in domain
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- debug:
   var: domain_list
  